### ISSUE TITLE
Corporate Reward Payout not listing who earned it

### ISSUE THREAD

**Issue by ryanrenn** [GoldenGnu/jeveassets#44] opened 2018-05-07 02:05 UTC
So I have a few guys who are running incursions.   In Jeveassets it lists nothing under From or To.

In game it reads as a "Corporate Reward Payout" - CONCORD rewarded *PlayerName* for services performed.

**Comment by GoldenGnu** [comment] 2018-05-07 15:45
Thank you for your bug report :)

Both `to` and `from` are optional in the ESI endpoint.
So, it's most likely because ESI does not return anything for those fields.
That said, jEveAssets currently using a deprecation version of the Journal endpoint.
A new version of jEveAssets will be released tomorrow (as XML dies), that uses the latest version of the endpoint. It may or may not fix the problem.

You can check if it's a ESI issue yourself on the [WebUI](https://esi.evetech.net/ui/#/Wallet/get_characters_character_id_wallet_journal).
If you can not reproduce the problem on the WebUI, please, return here and let me know.

**Comment by GoldenGnu** [comment] 2018-05-28 10:52
I assume this is the bug you’re talking about:
https://github.com/esi/esi-issues/issues/809#issuecomment-392490247
It’s going to be fixed tomorrow.

**Comment by GoldenGnu** [comment] 2018-05-31 19:47
This should be fixed in ESI now.
Please, leave a comment here if you’re still seeing this behavior on new journal entries.

**Closed by GoldenGnu** 2018-05-31 19:47 UTC
