### ISSUE TITLE
Stockpile Organization

### ISSUE THREAD

**Issue by Mr00Anderson** [GoldenGnu/jeveassets#362] opened 2023-02-05 13:49 UTC
With many stockpiles it could be useful to have some organization of them by structuring into folders. 

![image](https://user-images.githubusercontent.com/1356935/216823197-9c8492ac-c788-4b90-945c-2031b58b6240.png)

**Comment by GoldenGnu** [comment] 2023-02-19 21:43
Duplicate of Issue #321

**Closed** 2023-02-19 22:41 UTC
Labels: duplicate
