### ISSUE TITLE
Feature Request - Science job's within industry jobs

### ISSUE THREAD

**Issue by Sardaukai** [GoldenGnu/jeveassets#180] opened 2020-07-27 06:46 UTC
Hi,
maybe I am wrong, but i have never seen any industry jobs with my blueprints (copy / invention)

For stockpiling blueprints (copying) it would be really usefull if they would appear as an industry job.
For an invention it could be harder - in order not to calculate a chance - it could be an workaround to use plan numbers.
At least you know that you have started some jobs.

Cheers and thx for this great programm and support !!!

**Comment by GoldenGnu** [comment] 2020-07-27 09:46
Copy:
You can add blueprints as `Blueprints Runs`, that will keep track of how many BPC runs you have.
It also work with `Manufacturing` to keep track of how many BPC runs you're making.
Will that fit your need for copying?

Invention:
Since it's chance based, I'm not sure if it's a good fit for the stockpile, but, I'm open to discussing it.

**Comment by Sardaukai** [comment] 2020-07-27 16:21
Copy (Stockpile) is great  but 
copy job's did not appear within Industry Jobs column at Stockpile, maybe a bug?
I have tested this with Runs and BPC.

Invention:
It would be a major thing to implement correct % for inventions, so these values could be a "hint". In order to remember what you have started or what did you forget. I manage whole drones and charges (T1 & T2 runs) with this stockpile system - its really powerful. But I have to check all invetions twice in order not to forget one. That takes a lot of time.

**Comment by GoldenGnu** [comment] 2020-07-27 18:33
Copy: 
It does work, just tested it myself.
As, I said in my last post, you need to include `Manufacturing` for it to show up:
Edit the stockpile > Include > Check `Manufacturing`
Also, everything else still need to match (location/owner etc.).
If you can't get it to work, try making a stockpile for the entire universe and no other filters.
Then use trial and error until you got it working like you want.

Invention:
The chance of success (probability) is actually included in the ESI return for invention jobs, so, that is easy enough.
Could you explain a little more about your use case.
Do you just need to keep track of active invention jobs or do you also need to know the estimated output?

**Comment by NickvdMeij** [comment] 2020-10-15 07:39
Just adding to this conversation, since im also interested in having invention jobs listed. What would be perfect is the following:

- T2 BPC's are being tracked in assets, so you can actually have them in your stockpile
- Inventions jobs are visible and invention chances are being shown. If the T2 BPC is in a stockpile, it should calculate how many runs you need to do to get x amount of that T2 BPC

**Comment by Sardaukai** [comment] 2021-02-14 14:11
Hi,
.. it is a bit ago but here it is ;)
I hope it is ok to revive this post ^^


I tested some stuff, maybe it is a bug or a feature?  I do not know.
Maybe you can explain it to me ;) 

Version 6.7.1 portable
All tests done at an upwell! 
At corporation hangar.


Reactions / BPO in use loose container location
Name					Container						Flag
Carbon Polymers Reaction Formula	None							Industry Job  <-- in use
Carbon Polymers Reaction Formula	Office #... > Container (Station Container) #...	Unlocked      <-- free

Vespa I Blueprint (BPO)			None							Industry Job  <-- in use
Vespa I Blueprint (BPO)			Office #... > Container (Station Container) #...	Unlocked      <-- free

Both are stored in the same container. The first in in use. As you can see, it is no more in the Office / Container
It should stay at the container because it will remain after use. 
Is it possible to fix it? Or is there a reason why?


Production with a BPO let the BPC industry job count
To reproduce:
Use a BPO and produce X items of it.
Setup a stockpile with a BPC (Blueprint Copy) of that BPO with Industry Jobs marked. 
X is set as Industry Jobs running. Industry jobs for production should be ignored.


Copy jobs for "Blueprint Copy" are not mention
To reproduce:
Use a BPO for a copy job. At stockpile the BPC runs for it are ok, switching to copy's results in zero industry jobs.
It should count because runs are ignored at stockpile, the user only want to see the plain copy count.


Invention stuff
It would be great if invention will be count in inventory jobs. So it is possible to maintain big invention lists,
then you simply know what you have started or which item needs to.

As you said it is possible to calculate the output with the percentage. That will be great but in the end I only want 
to know if i started the invention or not.  

I try to explain a bit:
If you want to see how much Warrior II BPC you have, setup a stockpile for it (run or copy), 10 copys for example.
Atm there are 5 copys, so the stockpile is at 50%. 

Option A (with %)
A char starts inventions with 20 copys and a chance of 50%. Then
the industry count should be 10 copys. In sum the Warrior II BPC should have a surplus at 5 copys.

Option B (plain)
A char starts inventions with 20 copys. Then the industry count should be 20 copys. 
In sum the Warrior II BPC should have a surplus at 15 copys. In mind that it will be a lower amount because of %-chance


Cheers Sar

**Comment by GoldenGnu** [comment] 2021-02-14 17:14
> I hope it is ok to revive this post ^^

It end being really hard to track each issue when an issue contains multiple bug reports and feature requests.
So, I'm going to answer each section here the best I can and then you will have to create new issues for each issue, so, it will be possible to track them individually.

Missing container:
In short, jEveAssets consider the location of a blueprint in use to be the location it's being used at, not the output location. So, in jEveAssets's optic it's not in the container while it's being used. The main reason for this is that the container data is not available in the API while the blueprint is in use.

>Production with a BPO let the BPC industry job count

You will have to explain that in greater detail, I don't understand what the problem is.
But, you need to create a new issue for it.

> Copy jobs for "Blueprint Copy" are not mention

Again, you will have to explain this in greater detail, I don't understand what the problem is.
And, again, you need to create a new issue for it.

Invention stuff:
Please create a new issue for this feature request.
It does sound useful. It's a bigger task as it will require new static data be added (the output blueprint for invention), but, it's a good idea, I'm sure more people will find it useful.

I'm going to close this issue, as it end up going off topic. If you still want the initial issue resolved, please create a new issue for it.

**Closed by GoldenGnu** 2021-02-14 17:14 UTC
Labels: question
