### ISSUE TITLE
Historical values in "worth" tracker change unexpectedly

### ISSUE THREAD

**Issue by rossos** [GoldenGnu/jeveassets#42] opened 2018-03-27 04:29 UTC
One of my main uses for jeveassets is getting a nicer breakdown of "total net worth" across several characters, which the program does very nicely. Using Tools -> Worth -> Tracker, I can periodically import data (Update -> Update) and get nice graphs showing how various assets, market orders, contracts, etc. are moving up or down in value.

At least twice now, I have updated structures + performed a regular Update, only to find that *historical* data points are changing values, in both cases going down (so for instance, yesterday my total net worth from Feb. 14 might have been 100b, but today it shows as 83.5b).

I expect a certain amount of error and fluctuation in day-to-day assessments, due to lots of moving parts. But I can't account for *past* values dropping down by billions and billions of ISK for no obvious reason.

Both of these instances happened around a jeveassets update; could either an SDE update, or me updating the structures, cause the worth tracking to make a mistake? I don't know how far I should be trusting what jeveassets is telling me any more.

**Comment by rossos** [comment] 2018-04-04 17:45
Following up to say that these changes in historical values might be related to large quantities of stuff being moved in to and out of "Deliveries" hangars in citadels. Would jEveAssets makes changes to past values if something "disappeared" into a delivery hangar, assuming these hangars are not viewable yet via the the API?

**Comment by Shirrath** [comment] 2018-04-05 06:04
I've forgotten stuff in the delivery hangar several times, and I don't think the contents of the delivery hangar could cause retroactive changes; Whatever is in the delivery hangar is just not counted for that specific snapshot. If you realize your mistake, move the stuff away from the delivery hangar and do an another update, you should see a (corrective) spike in your net worth.

**Comment by darko8472** [comment] 2018-06-09 21:53
I've just had a similar issue crop up with the latest update to the program (5.6.0) - I've noticed for a while that the total asset value on the main list does not match the values in the tracker (tracker is lower) but with this latest update it's completely re-written my past data values.

**Comment by GoldenGnu** [comment] 2018-06-10 07:21
1:
Yes, 5.6.0 does rewrite the tracker points. Because, of all the invalid assets
From the change log:
> -Delete known invalid tracker asset locations

Those location have been deleted from the tracker, but, it's 100% certain that they never existed in game at the time the data point was created. It should cleanup a lot of invalid unknown locations in the tracker.

2:
Due the resaon I have not been able to figure out, some of the tracker asset filters have been unchecked.
See this post in the jEveAssets thread: https://forums.eveonline.com/t/jeveassets-5-6-0-2018-06-06/13255/223?u=golden_gnu

Let me know of the above solve your problems.

**Comment by darko8472** [comment] 2018-06-10 13:57
I did see some stations unchecked and have made sure they are all selected again - but still no noticeable difference.

Images: https://imgur.com/a/QBh7FGo

**Comment by GoldenGnu** [comment] 2018-06-13 05:45
@rossos @darko8472 
I'm going to need you to email me some data, so, I can reproduce it locally:
1) Go to the [settings location](https://github.com/GoldenGnu/jeveassets/wiki/ReadMe#settings-location)
2) I need the following files: 
   - `.jEveAssets\data\settings.xml`
   - `.jEveAssets\data\settings_5.6.0_backup.zip`
   - `.jEveAssets\data\settings_5.3.0.backup`
   - `.jEveAssets\profiles\#Default.xml`
3) Copy all the files to a new directory
4) Zip the directory
5) Email the zip file to me at: niklaskr@gmail.com

❗️ Please, note that the files I'm requesting contain all your jEveAssets data and should be considered private. Do not share/upload them anywhere public.

**Comment by GoldenGnu** [comment] 2018-06-23 10:45
Just a small update:
I'm able to reproduce the problem with darko8472's data set.
I will try to release a new version as soon as possible that fix this issue.

I will update this issue when the fix is released

**Comment by GoldenGnu** [comment] 2018-07-19 09:56
Another progress update

Fixing the bug:
The bug that disrupted darko8472's tracker will be fixed in the next release. It only affect version 5.6.0. I don't know what the original problem was (I think it started in 5.3.0, though).

Restoring order:
Since the damage is already done, I'm going to implement a new feature to import tracker data from a file. This will allow people with corrupted tracker data to import settings backup files (typically named either: `settings_5.6.0_backup.zip` or `settings_5.5.0.backup`), to restore as much data as possible.

@rossos
I would still like to take a look at your data, so, I can find the original problem. See my comment on the 13 Jun, for what I need to debug it.

**Comment by darko8472** [comment] 2018-07-19 12:10
Brilliant, thanks for the update. I did see the previous one and meant to reply sooner.

**Comment by GoldenGnu** [comment] 2018-07-31 12:13
Fixed released in 5.7.0
Please create a new issue, if you're still getting this bug

**Closed by GoldenGnu** 2018-07-31 12:13 UTC
Labels: bug, planned, tracker
