### ISSUE TITLE
jEveAssets: Stockpiles:  Blueprint Copy Runs shows 0 incorrectly

### ISSUE THREAD

**Issue by RobUSA** [GoldenGnu/jeveassets#262] opened 2021-07-15 18:18 UTC
A few weeks ago, an update to jEveAssets changed the behavior of Blueprint (Runs) in the Stockpile tool.  Within Eve, I have a bunch of tech II BPCs made via invention stored in Small Standard Containers in an NPC station.   In jEveAssets, I have a stockpile set up to show me the number of runs of each different BPC type I have in my inventory.   Prior to a few weeks ago in jEveAssets, the 'Total Stock' column showed all sorts of different numbers that appeared to accurately reflect what I had in game.  After installing an update, (almost) the entire 'Total Stock' column went to zero, even though I know stocks of BPCs still exist in my Eve Online account.  (There are a few item types that still show a correct/non-zero 'Total Stock' number, but I haven't been able to figure out the pattern of which do and which don't.  The large majority of them incorrectly show zero.)

To get extra-specific, in case it helps:

REPRO STEPS:
1. In Eve, complete an invention job for Multispectrum Coating II BPC, and place the BPC in a Small Standard Container in an NPC station, like Osaumuni CreoDron Factory.
2. In jEveAssets, under the 'Assets' tab, search (i.e. add a filter where name contains...) for 'Multispectrum Coating II Blueprint (BPC)'.  For my Eve Online character, I observe about 20 separate BPCs matching that filter, which is correct.
3. Open Stockpiles (jEveAssets menu bar > Tools > Inventory > Stockpile)
4. Click 'New Stockpile', named "Foo", for the Station Osaumuni CreoDron Factory, and set 'Include' to Assets.
5. Add an item to that new Stockpile.  For Item, type "Multispectrum Coating II Blueprint".  Set the Blueprint Type dropdown to "Blueprint Runs", and set Minimum Count to "100".  Hit Okay.
6. Look at the row for Multispectrum Coating and the number shown for Total Stock.

ACTUAL RESULT:
Unfortunately, 'Total Stock' shows zero.

EXPECTED RESULT: 
'Total Stock' should show about 200, since I know I have about 20 10-run copies Multispectrum Coating II Blueprints.  (Which jEveAssets itself confirms on the Assets tab.)

Anyway, I hope you can help me out with this!!  It seems like something that broke in a semi-recent update.  (A month ago, I think?)  Also:  jEveAssets is an awesome tool!!! I really appreciate all the work & time you've put into making such an incredible tool for Eve industrialist players, thank you!!!  Fly safe.  o7

**Comment by GoldenGnu** [comment] 2021-07-17 14:44
Sorry for the long response time. I'm going to look into this as soon as I have some spare time.

**Comment by GoldenGnu** [comment] 2021-07-18 13:23
Looks like it was introduced in 1bb42d95e8ab557a644cce216de68c24f39ea5b3
Should be easy enough to reproduce and fix.

**Comment by GoldenGnu** [comment] 2021-09-24 21:47
This should be fixed in the latest release.
@RobUSA Could you confirm if this is fixed or not? That would be super helpful, thank.

**Closed** 2022-02-22 17:55 UTC
Labels: bug, question, stockpile
