### ISSUE TITLE
Automatic update

### ISSUE THREAD

**Issue by Amme11** [GoldenGnu/jeveassets#73] opened 2018-10-25 06:41 UTC
Idk if this suggestion have been brought up or not, i would like to be able to set up so that the program updates at a certain time of the day or at certain intervals when the software is open. Also if the program could start at windows startup.

**Comment by deadlybulb** [comment] 2018-10-25 11:06
Let's take the easy one first.  To start jEveAssets (or any program) at windows startup, just copy a shortcut to your startup folder.  There are many articles on how to do this, here's one from microsoft: https://social.technet.microsoft.com/Forums/en-US/f0005629-0377-4e4b-82cc-26aff7b95884/how-do-you-add-new-startup-programs-in-wndows-10?forum=WinPreview2014General

Regarding regular updates, I assume you mean account updates.  The guidance so far has been to put your accounts on EveKit (https://evekit.orbital.enterprises), which keeps a full history of your account data even when you're not running jEveAssets.  Then, when you run jEveAssets, you can update and sync with EveKit and get all the updates you may have missed while offline.  Full disclosure, I'm the author of EveKit, but GoldenGnu has been giving the same advice.

It would be possible to add periodic updates to jEveAssets (modular refresh token handling), but I'm not sure where GG is on doing this, or if there are any plans at all.

**Comment by AnrDaemon** [comment] 2019-01-03 00:01
Dupe of #69

**Comment by GoldenGnu** [comment] 2019-02-04 20:45
Closing as duplicate #69 (thanks AnrDaemon)

**Closed by GoldenGnu** 2019-02-04 20:45 UTC
