### ISSUE TITLE
Corporation Structure roles

### ISSUE THREAD

**Issue by eve-n0rman** [GoldenGnu/jeveassets#85] opened 2019-03-16 20:13 UTC
For corp-only ESI keys, jeveassets doesn't appear to request esi-corporations.read_structures.v1 roles, or lookup corp structure names.  I have a structrure I'd like to use in a stockpile in a profile that only has corp keys.  As a result, structures I don't have personal assets in (in another profile) don't show up in the station menu in stockpiles.  Update>Structures is greyed out because none of the keys in the profile have structure roles.

**Comment by GoldenGnu** [comment] 2019-03-17 10:45
Yerh, that is by design, as the structure endpoint that resolves the structure names, only checks if the character have access (not the corporation), no matter if it's a jEveAssets corp or char account. So, by definition it's a character endpoint.

To the best of my knowledge you can't resolve structure names with
`esi-corporations.read_structures.v1`

Anyway, it's trivial to resolve: Add a character with access to the structure, and uncheck all scopes except structures, and you will be able to resolve your structure. 

I'm going to close this and mark as invalid.
If you disagree with the, feel free to leave a comment, nothing is final.

**Closed by GoldenGnu** 2019-03-17 10:45 UTC
