### ISSUE TITLE
Missing assets from POCOs and launchpads on selected characters

### ISSUE THREAD

**Issue by hellridergit** [GoldenGnu/jeveassets#464] opened 2024-05-29 13:52 UTC
Hi. 5 days ago I moved PI to another system on two characters,
the program sees the first character's PI products there (launchpads+POCO), but does not see the second character owning any Tier 2 materials at either the planets or their respective POCOs. The materials have in fact been there for days.

This was never an issue before.
jeveassets does not report cache issues, and it has lasted 5 days now.

I ruled out local data issue by wiping the program and `.\.jeveassets`, and installing it anew, importing characters anew (full ESI scopes).
It's been 2 days since and the situation remains the same.

Tested without using filters as well, and primary sorting `Group`, and scrolling to `Refined Commodities - Tier 2`.

jeveassets 7.9.0 on Windows 10 Pro [10.0.19045.4412]

**Comment by jpkoester1** [comment] 2024-05-29 18:09
If I recall correctly the ESI data on PI is only updated when an action is performed on the planet (export/import to POCO, transferring between launchpads, etc…, but not sure which actions exactly). You could try doing some export or import and then update jEveAssets. If the items show up, that was the issue. Otherwise I am sure GoldenGnu will have ideas…

**Comment by GoldenGnu** [comment] 2024-05-30 19:25
Yes that is correct, see #397
I’m planing to do #453 to make it easier to identity when the data is stale

I’m going to close this a duplicate of the above issue. If you’re able to verify it’s an jEveAssets issue and not the ESI above, please leave a comment with the details.

**Closed by GoldenGnu** 2024-05-30 19:25 UTC
