### ISSUE TITLE
Feature Request:   Add ability to reset only the sort order in the asset view

### ISSUE THREAD

**Issue by MaddMaxx2000** [GoldenGnu/jeveassets#183] opened 2020-08-10 13:42 UTC
Currently in the asset list view, you can click on the column names to sort the view based on that column.  You can then click on additional columns and nest the sort view in the order/hierarchy that you selected the columns. 

The only way to change the sort order is to reset the sort order back to default by right clicking on the column title bar and selecting 'Reset columns to default' which also resets the entire view - loosing any column adds/removes, the columns order, moving any added Jumps (Table->Jumps->Add_Custom) to the far right of the columns show.

Requested Change:   Add the ability to reset just the Sort Order and retain everything else.   Add a 'Reset sort order only' when right clicking on the column title bar.

**Comment by GoldenGnu** [comment] 2020-08-10 16:40
See: https://jeveassets.nikr.net/faq#sort_columns
Closed as duplicate of #40

**Closed by GoldenGnu** 2020-08-10 16:40 UTC
