### ISSUE TITLE
Update issue : Price Data EveMarketer.com errors

### ISSUE THREAD

**Issue by NanoPish** [GoldenGnu/jeveassets#82] opened 2019-03-04 22:30 UTC
When I update all, I get 

> Update issue : Price Data EveMarketer.com errors

With

> Price data Failed to update price data

Using 5.8.2 with evekit account mainchar and in game character Zien Lip

**Comment by deadlybulb** [comment] 2019-03-04 23:40
That's a known issue:

https://forums.eveonline.com/t/jeveassets-5-8-2-2019-03-04/13255/379

Try changing the price source to fuzzworks:

https://forums.eveonline.com/t/jeveassets-5-8-2-2019-03-04/13255/383

**Comment by GoldenGnu** [comment] 2019-03-05 03:26
Just tested EveMarketer and I'm not able to reproduce the problem.
Debugging this will require the log: [how to email a bug report](https://github.com/GoldenGnu/jeveassets/wiki/ReadMe#bugs)

**Comment by NanoPish** [comment] 2019-03-05 12:34
logfile https://ufile.io/zy86m

culprit ? : 

> INFO: [Price Fetching 2] uk.me.candle.eve.pricing.AbstractPricingFast - getting 48 prices
ERROR: [Price Fetching 2] uk.me.candle.eve.pricing.AbstractPricingFast - Error fetching price
javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1963)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1958)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1957)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1525)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:245)
	at uk.me.candle.eve.pricing.AbstractPricing.getInputStream(AbstractPricing.java:188)
	at uk.me.candle.eve.pricing.AbstractPricing.getElement(AbstractPricing.java:169)
	at uk.me.candle.eve.pricing.AbstractPricingFast.fetchPrices(AbstractPricingFast.java:63)
	at uk.me.candle.eve.pricing.AbstractPricing$PriceFetchingThread.run(AbstractPricing.java:450)
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:128)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at java.base/sun.security.ssl.Alert$AlertConsumer.consume(Alert.java:279)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:181)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1152)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1063)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:567)
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1581)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3033)
	at java.base/java.net.URLConnection.getContentEncoding(URLConnection.java:530)
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getContentEncoding(HttpsURLConnectionImpl.java:401)
	at uk.me.candle.eve.pricing.AbstractPricing.getInputStream(AbstractPricing.java:185)
	... 3 common frames omitted

**Comment by NanoPish** [comment] 2019-03-05 12:40
By the way if there a guide somewhere ? I see the faq but I don't know how to use this software, I have an empty window and all the tabs are empty (worth, inventory...)

**Comment by GoldenGnu** [comment] 2019-03-05 21:09
The issue with EveMarketer can most likely be resolved by updating to the latest version of Java 8: See [wiki](https://github.com/GoldenGnu/jeveassets/wiki/ReadMe#solutions-2)

There is also a short setup guide on the [wiki](https://github.com/GoldenGnu/jeveassets/wiki/ReadMe#add-charactercorporation).

**Comment by GoldenGnu** [comment] 2019-03-24 19:17
I'm going to close this as resolved. Please create a new issue, if anything in this issue is still unresolved.

**Closed by GoldenGnu** 2019-03-24 19:17 UTC
Labels: bug, question
