### ISSUE TITLE
All entries in stockpile window are duplicated.

### ISSUE THREAD

**Issue by ooeell** [GoldenGnu/jeveassets#60] opened 2018-08-17 19:27 UTC
Since a relatively recent update, all entries in the stockpile window are duplicated exactly twice.

Adding or removing any one entry refreshes the list, and the issue is corrected. This must be done during every app launch to get correct tables.

https://i.imgur.com/Ic7jC9o.png

**Comment by GoldenGnu** [comment] 2018-08-18 08:04
Thank you for your bug report.
I'm not able to reproduce it myself.

I would like you to email me the settings file, so I can reproduce it locally.
1) Go to the settings location's (see [wiki](https://github.com/GoldenGnu/jeveassets/wiki/ReadMe#settings-location))
2) In the `data` folder zip the `settings.xml` file
3) Email the zip file to niklaskr@gmail.com

I will look into as soon as I have the settings file.

**Comment by GoldenGnu** [comment] 2020-04-27 14:08
Going to close this, as I have never been able to reproduce it. Leave a comment to get the issue re-open in case it happens again.

**Closed by GoldenGnu** 2020-04-27 14:08 UTC
Labels: bug, stockpile
