### ISSUE TITLE
Crystals are showing up as hislot items is this ccp side or jeveassets side?

### ISSUE THREAD

**Issue by Neugeniko** [GoldenGnu/jeveassets#41] opened 2018-03-03 10:45 UTC
```
Pyroxeres Mining Crystal II	None	Mining Crystal	Charge	Neugeniko	Waira VIII - Moon 15 - Caldari Provisions Food Packaging	0.5	The Citadel	Diggy Diggy Hole (Skiff) #1020171536890	HiSlot0
Plagioclase Mining Crystal II	None	Mining Crystal	Charge	Mectoasinus	Kusomonmon V - Moon 9 - Caldari Navy Testing Facilities	0.8	The Citadel	Asterplus (Covetor) #1007473402989	HiSlot0
Veldspar Mining Crystal I	None	Mining Crystal	Charge	Mectoasinus	Mitsolen IV - Moon 12 - Core Complexion Inc. Warehouse	0.6	The Forge	Asteriod (Retriever) #1005485661594	HiSlot0
Veldspar Mining Crystal II	None	Mining Crystal	Charge	Mectoasinus	Kusomonmon V - Moon 9 - Caldari Navy Testing Facilities	0.8	The Citadel	Some (Procurer) #1019978334788	HiSlot0
Veldspar Mining Crystal II	None	Mining Crystal	Charge	Mectoasinus	Mitsolen IV - Moon 12 - Core Complexion Inc. Warehouse	0.6	The Forge	Octo (Hulk) #1009207088423	HiSlot0
Veldspar Mining Crystal II	None	Mining Crystal	Charge	Mectoasinus	Mitsolen IV - Moon 12 - Core Complexion Inc. Warehouse	0.6	The Forge	Turme (Skiff) #1009207176779	HiSlot0
Pyroxeres Mining Crystal II	None	Mining Crystal	Charge	Neugeniko	Waira VIII - Moon 15 - Caldari Provisions Food Packaging	0.5	The Citadel	Diggy Diggy Hole (Skiff) #1020171536890	HiSlot1
Plagioclase Mining Crystal II	None	Mining Crystal	Charge	Mectoasinus	Kusomonmon V - Moon 9 - Caldari Navy Testing Facilities	0.8	The Citadel	Asterplus (Covetor) #1007473402989	HiSlot1
Veldspar Mining Crystal I	None	Mining Crystal	Charge	Mectoasinus	Mitsolen IV - Moon 12 - Core Complexion Inc. Warehouse	0.6	The Forge	Asteriod (Retriever) #1005485661594	HiSlot1
Veldspar Mining Crystal II	None	Mining Crystal	Charge	Mectoasinus	Kusomonmon V - Moon 9 - Caldari Navy Testing Facilities	0.8	The Citadel	Some (Procurer) #1019978334788	HiSlot1
Veldspar Mining Crystal II	None	Mining Crystal	Charge	Mectoasinus	Mitsolen IV - Moon 12 - Core Complexion Inc. Warehouse	0.6	The Forge	Octo (Hulk) #1009207088423	HiSlot1
Scordite Mining Crystal II	None	Mining Crystal	Charge	Mectoasinus	Mitsolen IV - Moon 12 - Core Complexion Inc. Warehouse	0.6	The Forge	Turme (Skiff) #1009207176779	HiSlot1
Gamma L	None	Frequency Crystal	Charge	Neugeniko	Umokka X - Moon 4 - Caldari Navy Testing Facilities	0.6	Lonetrek	Party Boat (Typhoon) #1004654858018	HiSlot4
Infrared L	None	Frequency Crystal	Charge	Neugeniko	Umokka X - Moon 4 - Caldari Navy Testing Facilities	0.6	Lonetrek	Party Boat (Typhoon) #1004654858018	HiSlot5
Standard L	None	Frequency Crystal	Charge	Neugeniko	Umokka X - Moon 4 - Caldari Navy Testing Facilities	0.6	Lonetrek	Party Boat (Typhoon) #1004654858018	HiSlot6
```

**Comment by GoldenGnu** [comment] 2018-03-03 11:43
It looks like all those crystals are fitted/installed to ship miners (in the high slots). So, I would assume high slot is the correct flag?
If not, please explain why it should have another flag instead :)

**Comment by Neugeniko** [comment] 2018-03-03 12:00
It only happens to crystals not any other ammo. Also it stuffs up xml export of the loadout because it only expects 1 item per slot i guess. I dont think assets ever showed loaded ammo as a asset.

**Comment by GoldenGnu** [comment] 2018-03-03 12:28
I assume you’re using ESI?
The data is directly from CCP. I’m not sure if it can be categorized as a bug, it’s definitely an inconsistency that not all ammo is included/excluded.
It’s also a jEveAssets bug that fitting export is not working and I will release a fix for that as soon as I have some time to work on jEveAssets.
Thank you for your bug report :)

**Comment by Neugeniko** [comment] 2018-03-03 12:34
Yes using ESI. And fits come out but they just have charges in the highslots sometimes and no weapons/strip miners.

**Comment by GoldenGnu** [comment] 2020-04-27 14:11
Going to close this, as I have never been able to reproduce it. Leave a comment to get the issue re-open in case it happens again.

**Closed by GoldenGnu** 2020-04-27 14:11 UTC
Labels: assets, bug, esi bug
